#!/bin/bash

# note to self - NEED the space in the [ ] test
if [ -z "$1" ];  # have not provided a repo
then
	echo "Must supply a github project name"
	exit 1
fi

#if [ $1!="-h" ];
#then
#	echo "usage:$0 [repository_name] < [class_github_name_FILE]"
#	exit 1
#fi




echo "creating directories for assignment $1"

#mkdir $1

while read -r line; 
do 
	if [ -d $line ]; then
	   echo "directory exists - skipping"
	else
	   mkdir $line
	fi

	mkdir "$line/$1"; 
	curl -s -S "https://codeload.github.com/$line/$1/zip/master" > "$line/$1/$1.zip"
	sleep 10
	unzip -qq "$line/$1/$1.zip" -d "$line/$1/."

done

